spring:
  profiles: zone1
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
server:  
  port: 8081

endpoints:
  shutdown:
    enabled: true
    sensitive: false
sample:
  int:
    property: 312
  string:
    property: git backend
